#!/usr/bin/env julia
# Regenerate assets/gpu_metrics_layouts.toml — the field offsets `amd_gpu_metrics` decodes with —
# from the Linux kernel's kgd_pp_interface.h (struct gpu_metrics_v*). Run when the kernel adds a
# revision; the package loads the file at precompile time, nothing else changes:
#
#     curl -sL https://raw.githubusercontent.com/torvalds/linux/master/drivers/gpu/drm/amd/include/kgd_pp_interface.h > /tmp/kgd.h
#     julia tools/gen_gpu_metrics_layouts.jl /tmp/kgd.h          # writes assets/gpu_metrics_layouts.toml
#
# Offsets follow the C ABI (natural alignment, struct padded to its widest member); a second entry
# per revision gives the packed size, in case a driver emits the struct without implicit padding —
# the header's structure_size selects at run time, and a size matching neither yields `missing`.
# Plain Julia, no packages.

const SIZES = Dict("uint8_t" => 1, "uint16_t" => 2, "uint32_t" => 4, "uint64_t" => 8,
    "int8_t" => 1, "int16_t" => 2, "int32_t" => 4, "int64_t" => 8)
# kernel field name => the decoder's key
const WANT = Dict("throttle_status" => "throttle_status", "indep_throttle_status" => "indep_throttle_status",
    "average_gfx_activity" => "gfx_activity", "average_umc_activity" => "umc_activity",
    "average_socket_power" => "socket_power_W", "curr_socket_power" => "socket_power_W",
    "current_gfxclk" => "gfxclk_MHz", "temperature_hotspot" => "hotspot_C", "temperature_mem" => "mem_temperature_C",
    "accumulation_counter" => "accumulation_counter", "prochot_residency_acc" => "prochot_residency_acc",
    "ppt_residency_acc" => "ppt_residency_acc", "socket_thm_residency_acc" => "socket_thm_residency_acc",
    "vr_thm_residency_acc" => "vr_thm_residency_acc", "hbm_thm_residency_acc" => "hbm_thm_residency_acc")

function layout(src, consts, name; aligned)
    m = match(Regex("struct $name \\{(.*?)\\n\\};", "s"), src)
    m === nothing && return nothing
    off, maxal = 0, 2
    fields = Tuple{String, Int, Int, Int}[]
    for line in split(m[1], '\n')
        line = strip(first(split(first(split(line, "//")), "/*")))
        (isempty(line) || startswith(line, "*")) && continue
        if startswith(line, "struct metrics_table_header")
            off += 4
            continue
        end
        f = match(r"^(\w+)\s+(\w+)(?:\[(\w+)\])?(?:\[(\w+)\])?;", line)
        f === nothing && continue
        t, n, a1, a2 = f.captures
        sz = SIZES[t]
        cnt = 1
        for a in (a1, a2)
            a === nothing && continue
            cnt *= get(consts, a, all(isdigit, a) ? parse(Int, a) : 0)
        end
        aligned && off % sz != 0 && (off += sz - off % sz)
        maxal = max(maxal, sz)
        push!(fields, (String(n), off, sz, cnt))
        off += sz * cnt
    end
    aligned && off % maxal != 0 && (off += maxal - off % maxal)
    return off, fields
end

# Vendor driver variants of an upstream struct: (format, content, upstream size) => (variant size,
# note). AMD's DKMS amdgpu (ROCm 6.3-era, 6.10.x) ships a v1.6 with `uint16_t num_partition` and
# `struct amdgpu_xcp_metrics xcp_stats[NUM_XCP]` appended before the final
# pcie_lc_perf_other_end_recovery, so every field this package reads sits at the upstream offsets and
# only structure_size differs (1664). Regeneration re-emits these from the upstream entry.
const VENDOR_VARIANTS = Dict(
    (1, 6, 312) => (1664, "AMD DKMS amdgpu 6.10 (ROCm 6.3): upstream v1.6 + num_partition + xcp_stats[NUM_XCP] appended; leading fields identical"),
)

function main(path, out)
    src = read(path, String)
    consts = Dict(m[1] => parse(Int, m[2]) for m in eachmatch(r"#define\s+((?:NUM|MAX)_\w+)\s+(\d+)", src))
    io = IOBuffer()
    println(io, "# Generated by tools/gen_gpu_metrics_layouts.jl from the Linux kernel's")
    println(io, "# drivers/gpu/drm/amd/include/kgd_pp_interface.h (struct gpu_metrics_v*); do not edit by hand.")
    println(io, "# One [[layout]] per (format, content, structure_size): the C-aligned size and, where it differs,")
    println(io, "# the packed size. fields.<name> = [byte offset, width in bytes, count]. Entries marked")
    println(io, "# \"vendor variant\" come from the generator's VENDOR_VARIANTS table, not from the header.")
    seen = Set{Tuple{Int, Int, Int}}()
    emitted = Dict{Tuple{Int, Int, Int}, Vector{Tuple{String, Int, Int, Int}}}()
    revisions = vcat([(1, i) for i in 0:8], [(2, i) for i in 0:4])
    for (fmt, con) in revisions, aligned in (true, false)
        r = layout(src, consts, "gpu_metrics_v$(fmt)_$(con)"; aligned)
        r === nothing && continue
        size, fields = r
        (fmt, con, size) in seen && continue
        push!(seen, (fmt, con, size))
        emitted[(fmt, con, size)] = fields
        println(io, "\n[[layout]]\nformat = $fmt\ncontent = $con\nsize = $size   # $(aligned ? "C-aligned" : "packed")")
        println(io, "[layout.fields]")
        for (n, o, sz, c) in fields
            haskey(WANT, n) && println(io, "$(WANT[n]) = [$o, $sz, $c]")
        end
    end
    for (base, (vsize, note)) in sort(collect(VENDOR_VARIANTS))
        haskey(emitted, base) || (println(stderr, "vendor variant of $base: base layout not generated, skipped"); continue)
        (base[1], base[2], vsize) in seen && continue
        push!(seen, (base[1], base[2], vsize))
        println(io, "\n[[layout]]\nformat = $(base[1])\ncontent = $(base[2])\nsize = $vsize   # vendor variant of the $(base[3])-byte entry: $note")
        println(io, "[layout.fields]")
        for (n, o, sz, c) in emitted[base]
            haskey(WANT, n) && println(io, "$(WANT[n]) = [$o, $sz, $c]")
        end
    end
    write(out, take!(io))
    println(stderr, "wrote $out ($(length(seen)) layouts)")
end

1 <= length(ARGS) <= 2 || (println(stderr, "usage: julia tools/gen_gpu_metrics_layouts.jl <kgd_pp_interface.h> [out.toml]"); exit(64))
main(ARGS[1], get(ARGS, 2, joinpath(@__DIR__, "..", "assets", "gpu_metrics_layouts.toml")))
